### PR TITLE
text: Fix x11 session logic.

### LINKED ISSUE #18: Find the right clipboard commands
#17 was a major improvement on the goal of setting the right clipboard command. [I found out that it may be the case that a user is using X11 but `XDG_SESSION_TYPE` is set to `tty` instead of `x11`](https://discourse.atlas.engineer/t/unable-to-copy-paste/850/5). I suggest to fallback on `xclip` or `xsel` if they're found regardless of the value of `XDG_SESSION_TYPE`. In other words, check `XDG_SESSION_TYPE` for Wayland exclusively.

@aartaka you run StumpWM, correct? What's the output of `env | grep XDG_SESSION_TYPE`?

### LINKED ISSUE #3347: Copy/Paste not working
Hello,
I may need your help.
I get the following error when trying to copy paste : 

```
WARN - Warning: Error on separate thread: Couldn't execute &quot;wl-paste&quot;: Aucun fichier ou dossier de ce type
```

I installed Nyxt from sources today.

**Information**
- OS name+version: Debian 12 Bookworm stable
- Graphics card and driver: Mesa Intel® HD Graphics 4000 (IVB GT2)
- Desktop environment / Window manager name+version: Gnome Shell 43.9
- How you installed Nyxt (Guix pack, package manager, build from source): Built from source. Cloned today.
- Information from `nyxt --system-information`:
```
Nyxt version: 4
Renderer: GI-GTK
Operating system kernel: Linux 6.1.0-18-amd64
Lisp implementation: SBCL 2.2.9.debian (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT-2.42.5
 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-4
 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS
 :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CLOSER-MOP
 :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/lambdarat/tools/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/lambdarat/tools/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/lambdarat/tools/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**

```
Nyxt version 4
<INFO> [11:22:41] Source location: #P"/home/lambdarat/tools/nyxt/"
<INFO> [11:22:41] Loading Lisp file #P"/home/lambdarat/.config/nyxt/config.lisp".
<INFO> [11:22:41] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"

(nyxt:91806): Gtk-CRITICAL **: 11:22:42.076: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(WebKitWebProcess:2): Gtk-WARNING **: 11:22:42.537: Theme parsing error: gtk.css:2:123: Failed to import: Erreur lors de l’ouverture du fichier /home/lambdarat/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/always.css : Aucun fichier ou dossier de ce type
<INFO> [11:22:42] Loading #P"/home/lambdarat/.local/share/nyxt/history/default.lisp".

(WebKitWebProcess:2): Gtk-WARNING **: 11:22:42.873: Theme parsing error: gtk.css:2:123: Failed to import: Erreur lors de l’ouverture du fichier /home/lambdarat/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/always.css : Aucun fichier ou dossier de ce type
<INFO> [11:22:42] Restoring 4 buffers from history.
<INFO> [11:22:43] Loading #P"/home/lambdarat/.local/share/nyxt/auto-rules.lisp".

(WebKitWebProcess:2): Gtk-WARNING **: 11:22:43.203: Theme parsing error: gtk.css:2:123: Failed to import: Erreur lors de l’ouverture du fichier /home/lambdarat/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/always.css : Aucun fichier ou dossier de ce type

(WebKitWebProcess:2): Gtk-WARNING **: 11:22:44.357: Theme parsing error: gtk.css:2:123: Failed to import: Erreur lors de l’ouverture du fichier /home/lambdarat/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/always.css : Aucun fichier ou dossier de ce type
<INFO> [11:22:45] Loading "https://github.com/atlas-engineer/nyxt/issues/new/choose".
<WARN> [11:22:45] Warning: Error while processing the "nyxt:" URL: There is no applicable method for the generic function #&lt;STANDARD-GENERIC-FUNCTION NYXT:STYLE (16)&gt; when called with arguments (NIL).
See also:
  The ANSI Standard, Section 7.6.6
<INFO> [11:22:46] Finished loading "https://github.com/atlas-engineer/nyxt/issues/new/choose".
<WARN> [11:22:48] Warning: Error on separate thread: Couldn't execute &quot;wl-paste&quot;: Aucun fichier ou dossier de ce type
```

Thank you in advance !
Arnaud

### PR DESCRIPTION
**Pull request by aadcg**
Fixes #18.

Fixes https://github.com/atlas-engineer/nyxt/issues/3347.

@snmsts please merge, thanks.

### CODE REVIEW

**Comment by aadcg** [comment]
Friendly ping @snmsts.

If you need help to maintain the library, feel free to give me the necessary rights. Thanks.

**Comment by snmsts** [comment]
Thanks for your patch and ping.
I understand it works well as a work around. but I don't like the style.

if it is written with

```
(find (uiop:getenvp "XDG_SESSION_TYPE") '("x11" "TTY?" ...) :test 'string=)
```

I'll merge immediately.

Thank you.

**Comment by aadcg** [comment]
I've made the suggested changes @snmsts, thanks.

**Comment by snmsts** [comment]
Thanks.

**Pull request merged**
