### PR TITLE
Make `text` a `setf`-able method.

### PR DESCRIPTION
**Pull request by aartaka**
This turns `text` into a method, thus making it:
- Advisable with `:before`, `:after`, and `:around` qualifier methods.
- Specializeable over types other than strings (arrays? images? objects? -- the possibilities are endless :D)
- Type-checking (well, only for the `seft`-method, but there's not much need in type-checking there ¯\\\_(ツ)_/¯)
- `seft`-able (would work for a function too, actually, but method gives us typing and other niceties for free).

I've tried to preserve backwards-compatibility, although I have initially tried to remove the `&optional data` too, so that it's even nicer of an API. However, I don't want to break anyone's workflows without an explicit version bump. Thus, @snmsts, are you willing to release a new version with method-based `text` and without the optional `data` argument?

### CODE REVIEW

**Comment by snmsts** [comment]
I don't see any practical benefit with this change so far and changing API is quite big deal.
versioning would automatically affect many of us because fixing version is rarely seen in cl world.

**Comment by aartaka** [comment]
Yes, those are valid concerns and the ones I haven't included the backwards-incompatible changes into this PR because of. Now that we resolved the possibility of changing the API, how does the code look like to you?

**Comment by aartaka** [comment]
Note that even though I added a `setf` method, one can freely use the old `&optional` argument and it will work just fine. Nothing to change in the software relying on `trivial-clipboard`!

**Comment by aartaka** [comment]
@snmsts, so, what's your verdict given that this PR is backwards-compatible?

**Comment by aartaka** [comment]
@snmsts, friendly ping :)

**Comment by aartaka** [comment]
Closing in favor of #12.

**Comment by snmsts** [comment]
sorry. I think at least it shouldn't be named ``text`` because it seems different.

**Comment by aartaka** [comment]
But it is named `text`...

`(setf text)` creates a certain handler for the times when you do `(setf (text ...) ...)`, it does not generate a new method to be called by the user.

**Comment by aartaka** [comment]
Oh wait, I've misread your comment. What is it different in? It's still a function that does exactly what `text` used to do, it's just a generic function with an added `setf` method. I don't see where it's different.

**Comment by snmsts** [comment]
I think I might over think about it. The purpose of defmethod here is just for make the function setf-able but generic function means more for users. people would start thinking how to use advice or define method for it if interface is generic function.

Would you hate defsetf ?

**Comment by aartaka** [comment]
> I think I might over think about it. The purpose of defmethod here is just for make the function setf-able but generic function means more for users. people would start thinking how to use advice or define method for it if interface is generic function.

That's the intended use-case :D We need to advise the clipboard operations in [Nyxt](https://github.com/atlas-engineer/nyxt) to ensure that our internal clipboard is in sync with the system one. `defmethod text :after` is a perfect use-case here.

> Would you hate defsetf ?

For this particular case -- yes. It's more extensible and transparent having a `setf`-method instead of a `defsetf`-generated macro :japanese_ogre:

**Pull request closed without merging**
